---
registry:
  - namespace:
    - :dchbx
    - :enroll_app
    features:
      - key: :aca_shop_market
        # item: # 'feature:<feature-key>'/'namespace:<feature-key>'
        is_enabled: true
        meta:
          label: 'ACA Shop Market'
          content_type: :feature_enabled
          description: Employer Sponsored Benefits Offered
          is_required: true
          is_visible: true
      - key: :aca_individual_market
        is_enabled: true
        meta:
          label: 'ACA Individual Market'
          content_type: :feature_enabled
          description: Individual Benefits Offered
          is_required: true
      - key: :congressional_market
        is_enabled: true
        meta:
          label: 'Congressional Market'
          content_type: :feature_enabled
          description: Congressional Benefits Offered
          is_required: true
          is_visible: true
  - namespace:
      path:
        - :dchbx
        - :enroll_app
        - :aca_shop_market
      meta:
        label: ACA Shop
        content_type: :feature_list
        description: 'ACA Shop Market Settings'
        is_required: true
        is_visible: true
    features:
      - key: :benefit_market_catalogs_configuration
        item: BenefitMarkets::Operations::BenefitMarketCatalogs::Configure.new
        is_enabled: true
        meta:
          label: Benefit Market Catalogs
          content_type: :model_attributes
          default: :''
          description: Configurations for Benefit Market Catalogs
          is_required: true
          is_visible: true
        settings:
          - key: :filter_params
            meta:
              label: Select Plan Year
              content_type: :filter
              default: :''
              description: Select Benefit Market Catalog Calender Year
              is_required: true
            item:
              criteria:
                market_kind: :aca_shop
              name: :effective_year
          - key: :model_query_params
            item:
              market_kind: :aca_shop
          - key: :title
            item:
              attribute: :title
              constraints:
                max_length: 20
            meta:
              label: Catalog Title
              content_type: :text_field
              description: Enter market catalog title
              is_required: false
              is_visible: true
          - key: :description
            item:
              attribute: :description
              constraints:
                max_length: 200
            meta:
              label: Catalog Description
              content_type: :text_field
              description: Enter market catalog description
              is_required: false
              is_visible: true
      - key: :health_packages
        is_enabled: true
        item: :features_display
        meta:
          label: Health Packages
          content_type: :nav
          default: :''
          description: 'Configurations for Health Product Packages'
          is_required: true
          is_visible: true
        settings:
          - key: :product_packages
            item:
              - :health_product_package_2021
              - :health_product_package_2020
            meta:
              label: Product Packages
              content_type: :feature_group
              description: product packages
              is_required: false
              is_visible: true
  - namespace:
    - :dchbx
    - :enroll_app
    - :aca_shop_market
    - :health_product_packages
    features:
      - key: :shop_product_package_clone
        item: ResourceRegistry::Operations::Features::Clone.new
        is_enabled: true
        meta:
          label: Shop Product Package Clone
          content_type: :legend
          default: nil
          description: Clone shop product packages
          is_required: false
          is_visible: true
        settings:
          - key: :calender_year
            item: nil
            meta:
              label: Calender Year
              content_type: :select
              description: Choose calender year for new product package
              enum: <%= [Date.today.year + 1, Date.today.year + 2].reduce([]) {|values, date| values << [date, date]} %>
              is_required: false
              is_visible: true
      - key: :health_product_package_2021
        is_enabled: true
        item: :feature_collection
        meta:
          label: Health Product Package 2021
          content_type: :legend
          default: true
          description: Health Product Pacakge for 2021
          is_required: true
          is_visible: true
        settings:
          - key: :contribution_models
            item:
              - :initial_sponsor_jan_default_2021
              - :initial_sponsor_default_2021
              - :renewal_sponsor_jan_default_2021
              - :renewal_sponsor_default_2021
            meta:
              label: Contribution Models
              content_type: :feature_list_panel
              description: Contribution Models
              is_required: false
              is_visible: true
          - key: :clone
            item: "/exchanges/configurations/shop_product_package_clone/edit"
            meta:
              label: Clone Product Package
              content_type: :feature_action
              description: Clone Product Packages for the given calender year
              is_required: false
              is_visible: true
      - key: :health_product_package_2020
        is_enabled: true
        item: :feature_collection
        meta:
          label: Health Product Package 2020
          content_type: :legend
          default: true
          description: Health Product Pacakge for 2020
          is_required: true
          is_visible: true
        settings:
          - key: :contribution_models
            item:
              - :initial_sponsor_jan_default_2020
              - :initial_sponsor_default_2020
              - :renewal_sponsor_jan_default_2020
              - :renewal_sponsor_default_2020
            meta:
              label: Contribution Models
              content_type: :feature_list_panel
              description: Contribution Models
              is_required: false
              is_visible: true
  - namespace:
    - :dchbx
    - :enroll_app
    - :aca_shop_market
    - :dental_product_packages
    features:
      - key: :2021_dental_contribution_models
        is_enabled: true
      - key: :2020_dental_contribution_models
        is_enabled: true