default: --format pretty --fail-fast --order random --strict --tags 'not @wip and not @broken and not @flaky and not @ma_only' --publish-quiet -r features --profile semaphoreci
everything: --format pretty --publish-quiet --strict -r features
semaphoreci: -q
flaky: --tags '@flaky and @broken' --publish-quiet
gh-report: --format json --out ci/cucumber/gh-cucumber-report.json --fail-fast --strict --tags 'not @wip and not @broken and not @flaky and not @ma_only' -r features
local-report: --format json --out ci/cucumber/local-cucumber-report.json --fail-fast --strict --tags 'not @wip and not @broken and not @flaky and not @ma_only' -r features
max_run: --format pretty --order random --strict --tags 'not @wip and not @broken and not @ma_only' --publish-quiet -r features
