default: --format 'pretty' --strict --tags  'not @wip' --tags 'not @ma_only' --tags 'not @quoting_enabled' --tags 'not @edit_aptc' --tags 'not @more_than_sole_source' --format summary --out tmp/cucumber.summary --format rerun --out tmp/cucumber_failures.log -r features  
wip: --tags @wip:11 --wip features
rerun: --format progress features --format rerun --out rerun.txt --strict --tags ~@wip
screenshots: --format 'pretty' --strict --tags  'not @wip' --tags 'not @ma_only' --tags 'not @quoting_enabled' --tags 'not @edit_aptc' --tags 'not @more_than_sole_source' -r features SCREENSHOTS=true
