wip: --tags @wip:11 --wip features
rerun: --format rerun --out rerun.txt --strict --tags ~@wip
screenshots: -r features SCREENSHOTS=true
semaphoreci: --format rerun --out tmp/cucumber_failures.log
default: -r features --profile semaphoreci
