name: yard doc generation
on:
  push:
    paths:
      - 'hugo/**'

jobs:
  docs_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: nelonoel/branch-name@v1.0.1
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install global packages
        run: |
          yarn install
          npm install -g postcss postcss-cli autoprefixer
      - run: sudo snap install hugo --channel=extended
      - run: cd hugo && hugo --minify
      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.YARD_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.YARD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YARD_SECRET_ACCESS_KEY }}
          SOURCE_DIR: hugo/public
          DEST_DIR: ${{ env.BRANCH_NAME }}
