name: Rspec and Cucumbers

on: push

jobs:
  rspec:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04] #ubuntu-16.04
        node: [10]
        mongodb-version: ["4.0", "4.2"]

    steps:
    - name: Launch MongoDB
      uses: wbari/start-mongoDB@v0.2
      with:
        mongoDBVersion: ${{ matrix.mongodb-version }}
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
        version: 10.16.3
    - name: bundle install, yarn install
      run: |
        gem update --system
        gem install bundler
        bundle install --jobs 4 --retry 3
        yarn install
        ./bin/webpack
    - name: rspec
      run:  bundle exec rspec ./spec/models/factories/eligibility_factory_spec.rb:268
    # Need to fix sbc_preprocessor2015_spec.rb
    #- name: rake parallel:spec[4]
    #  run:  bundle exec rake "parallel:spec[4]"
